import {
  PUBLIC_MIN_PASSWORD_LENGTH as ENV_MIN_PASSWORD_LENGTH,
  PUBLIC_MAX_PASSWORD_LENGTH as ENV_MAX_PASSWORD_LENGTH,
  PUBLIC_MIN_DISPLAY_NAME_LENGTH as ENV_MIN_DISPLAY_NAME_LENGTH,
  PUBLIC_MAX_DISPLAY_NAME_LENGTH as ENV_MAX_DISPLAY_NAME_LENGTH,
  PUBLIC_MIN_FIRST_NAME_LENGTH as ENV_MIN_FIRST_NAME_LENGTH,
  PUBLIC_MAX_FIRST_NAME_LENGTH as ENV_MAX_FIRST_NAME_LENGTH,
  PUBLIC_MIN_LAST_NAME_LENGTH as ENV_MIN_LAST_NAME_LENGTH,
  PUBLIC_MAX_LAST_NAME_LENGTH as ENV_MAX_LAST_NAME_LENGTH,
  PUBLIC_MIN_EMAIL_LENGTH as ENV_MIN_EMAIL_LENGTH,
  PUBLIC_MAX_EMAIL_LENGTH as ENV_MAX_EMAIL_LENGTH,
  PUBLIC_EMAIL_VERIFICATION,
} from '$env/static/public';

export const MIN_PASSWORD_LENGTH = Number.parseInt(ENV_MIN_PASSWORD_LENGTH);
export const MAX_PASSWORD_LENGTH = Number.parseInt(ENV_MAX_PASSWORD_LENGTH);
export const MIN_DISPLAY_NAME_LENGTH = Number.parseInt(ENV_MIN_DISPLAY_NAME_LENGTH);
export const MAX_DISPLAY_NAME_LENGTH = Number.parseInt(ENV_MAX_DISPLAY_NAME_LENGTH);
export const MIN_FIRST_NAME_LENGTH = Number.parseInt(ENV_MIN_FIRST_NAME_LENGTH);
export const MAX_FIRST_NAME_LENGTH = Number.parseInt(ENV_MAX_FIRST_NAME_LENGTH);
export const MIN_LAST_NAME_LENGTH = Number.parseInt(ENV_MIN_LAST_NAME_LENGTH);
export const MAX_LAST_NAME_LENGTH = Number.parseInt(ENV_MAX_LAST_NAME_LENGTH);
export const MIN_EMAIL_LENGTH = Number.parseInt(ENV_MIN_EMAIL_LENGTH);
export const MAX_EMAIL_LENGTH = Number.parseInt(ENV_MAX_EMAIL_LENGTH);

export const EMAIL_VERIFICATION = PUBLIC_EMAIL_VERIFICATION === 'true' || PUBLIC_EMAIL_VERIFICATION === '1';

export const DO_NOT_TRACK_COOKIE_NAME = 'cicipanel_do_not_track';
export const DISCLAIMER_DISMISSED_COOKIE_NAME = 'cicipanel_disclaimer-dismissed';
