import {
  PUBLIC_MIN_PASSWORD_LENGTH,
  PUBLIC_MAX_PASSWORD_LENGTH,
  PUBLIC_MIN_DISPLAY_NAME_LENGTH,
  PUBLIC_MAX_DISPLAY_NAME_LENGTH,
  PUBLIC_MIN_FIRST_NAME_LENGTH,
  PUBLIC_MAX_FIRST_NAME_LENGTH,
  PUBLIC_MIN_LAST_NAME_LENGTH,
  PUBLIC_MAX_LAST_NAME_LENGTH,
  PUBLIC_MIN_EMAIL_LENGTH,
  PUBLIC_MAX_EMAIL_LENGTH,
  PUBLIC_ALLOW_REGISTERS,
  PUBLIC_ENABLE_EMAIL_VERIFICATION,
  PUBLIC_ENABLE_PASSWORD_RESETS,
  PUBLIC_ENABLE_GRANULAR_PERMISSIONS,
  PUBLIC_ENABLE_THEMES,
  PUBLIC_ENABLE_RATE_LIMIT,
  PUBLIC_ENABLE_GITHUB_LINK,
} from '$env/static/public';

export const MIN_PASSWORD_LENGTH = Number.parseInt(PUBLIC_MIN_PASSWORD_LENGTH);
export const MAX_PASSWORD_LENGTH = Number.parseInt(PUBLIC_MAX_PASSWORD_LENGTH);
export const MIN_DISPLAY_NAME_LENGTH = Number.parseInt(PUBLIC_MIN_DISPLAY_NAME_LENGTH);
export const MAX_DISPLAY_NAME_LENGTH = Number.parseInt(PUBLIC_MAX_DISPLAY_NAME_LENGTH);
export const MIN_FIRST_NAME_LENGTH = Number.parseInt(PUBLIC_MIN_FIRST_NAME_LENGTH);
export const MAX_FIRST_NAME_LENGTH = Number.parseInt(PUBLIC_MAX_FIRST_NAME_LENGTH);
export const MIN_LAST_NAME_LENGTH = Number.parseInt(PUBLIC_MIN_LAST_NAME_LENGTH);
export const MAX_LAST_NAME_LENGTH = Number.parseInt(PUBLIC_MAX_LAST_NAME_LENGTH);
export const MIN_EMAIL_LENGTH = Number.parseInt(PUBLIC_MIN_EMAIL_LENGTH);
export const MAX_EMAIL_LENGTH = Number.parseInt(PUBLIC_MAX_EMAIL_LENGTH);
export const MIN_MOBILE_LENGTH = 5;
export const MAX_MOBILE_LENGTH = 32;

export const ALLOW_REGISTERS =
  (PUBLIC_ALLOW_REGISTERS ?? '').trim().toUpperCase() === 'true'
  || (PUBLIC_ALLOW_REGISTERS ?? '').trim() === '1';

export const ENABLE_EMAIL_VERIFICATION =
  (PUBLIC_ENABLE_EMAIL_VERIFICATION ?? '').trim().toUpperCase() === 'true'
  || (PUBLIC_ENABLE_EMAIL_VERIFICATION ?? '').trim() === '1';

export const ENABLE_PASSWORD_RESETS =
  (PUBLIC_ENABLE_PASSWORD_RESETS ?? '').trim().toUpperCase() === 'true'
  || (PUBLIC_ENABLE_PASSWORD_RESETS ?? '').trim() === '1';

export const ENABLE_GRANULAR_PERMISSIONS =
  (PUBLIC_ENABLE_GRANULAR_PERMISSIONS ?? '').trim().toUpperCase() === 'true'
  || (PUBLIC_ENABLE_GRANULAR_PERMISSIONS ?? '').trim() === '1';

export const ENABLE_THEMES =
  (PUBLIC_ENABLE_THEMES ?? '').trim().toUpperCase() === 'true'
  || (PUBLIC_ENABLE_THEMES ?? '').trim() === '1';

export const ENABLE_RATE_LIMIT =
  (PUBLIC_ENABLE_RATE_LIMIT ?? '').trim().toUpperCase() === 'true'
  || (PUBLIC_ENABLE_RATE_LIMIT ?? '').trim() === '1';

export const ENABLE_GITHUB_LINK =
  (PUBLIC_ENABLE_GITHUB_LINK ?? '').trim().toUpperCase() === 'true'
  || (PUBLIC_ENABLE_GITHUB_LINK ?? '').trim() === '1';

export const DO_NOT_TRACK_COOKIE_NAME = 'cicipanel_do_not_track';
export const DISCLAIMER_DISMISSED_COOKIE_NAME = 'cicipanel_disclaimer-dismissed';
